#cloud-config
package_update: true
package_upgrade: true
packages:
  - apache2
runcmd:
  - systemctl enable apache2
  - curl -s -H Metadata:true --noproxy "*" "http://169.254.169.254/metadata/instance/compute?api-version=2021-02-01" | sudo tee /var/www/html/index.html